name: Rishabh Jain

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
title:            Rishabh Jain
description:      "Full-Stack JavaScript Developer"
disqus_shortname: rishabh1403
url:              http://rishabh1403.com
permalink: /blog/:year/:month/:day/:title

# gems:
#   - jekyll-seo-tag
#   - jekyll-sitemap
